import type { NextPage } from 'next'
import Head from 'next/head'
import Post from "../components/Post/Post";
import Slider from "../components/Slider/Slider";
import {useEffect} from "react";
import {useAppDispatch, useAppSelector} from "../store/store";
import { fetchPosts} from "../store/dataReducer";
import {Layout} from "antd";
const Home: NextPage = () => {
    const isLoading=useAppSelector(state => state.data.isLoading)
    const posts=useAppSelector(state => state.data.posts);
    const dispatch=useAppDispatch();
    useEffect(()=>{
        dispatch(fetchPosts());
    },[])
  return (
      <Layout>
          <Head>
              <title>Blog App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
          </Head>
          {!isLoading &&
              <div style={{marginRight: 5}}>
                    <Slider posts={posts}/>
                          {posts.map(post=><Post key={post.node.id} post={post.node}/>)}
              </div>
                   }
      </Layout>


  )
}

export default Home
